workflows:
  android:
    name: Build Android APK
    max_build_duration: 60
    scripts:
      - name: Use JDK 17
        script: |
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $CM_ENV
          export JAVA_HOME=$JAVA_HOME_17_X64
          java -version
      - name: Build debug APK (wrapper or system Gradle)
        script: |
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            ./gradlew assembleDebug
          else
            echo "gradlew not found, using system Gradle"
            gradle --version || true
            gradle assembleDebug
          fi
    artifacts:
      - app/build/outputs/**/*.apk
