workflows:
  android:
    name: Build Android APK
    max_build_duration: 60
    scripts:
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug || gradle assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
